management:
    endpoints:
        web:
            exposure:
                include: "*"

cds:
    security.mock.users:
      - name: rose
        tenant: t1
      - name: martha
        tenant: t1
        roles:
        - reviewer
      - name: amy
        tenant: t1
        roles:
        - processor
      - name: admin
        tenant: t1
        password: admin
        roles:
        - admin
    remote.services:
      - "RemoteReviewService"

---
spring:
    config.activate.on-profile: default
    web.resources.static-locations: "file:./app"
logging.level.com.sap.cds.messaging: DEBUG
cds:
    odata-v4:
        endpoint:
            path: "/"

server:
    port: 8080


---
spring:
  config.activate.on-profile: local-mtxs
cds:
  data-source:
    auto-config.enabled: true
  multi-tenancy:
    compatibility.enabled: false
    mtxs.enabled: true
    sidecar.url: http://localhost:4005
  messaging:
    services:
    - name: "messaging"
      kind: "file-based-messaging"
      binding: "local-messaging.txt"

---
spring:
    config.activate.on-profile: cloud
    sql.init.mode: never

cds:
    datasource:
        csv.initialization-mode: never
    odata-v4:
        endpoint:
            path: "/"
