management:
    endpoints:
        web:
            exposure:
                include: "*"
logging.level:
    root: ERROR
    com.sap.cds.persistence: DEBUG
    com.sap.cds.handlers: DEBUG
spring:
    web.resources.static-locations: "file:./app"
cds:
    odata-v4.endpoint.path: "/"
    security.mock.users:
      - name: rose
        tenant: t1
      - name: martha
        tenant: t1
        roles:
        - reviewer
      - name: amy
        tenant: t1
        roles:
        - processor
      - name: admin
        tenant: t1
        password: admin
        roles:
        - admin
    remote.services:
      - "RemoteReviewService"

---
spring:
  config.activate.on-profile: default
  sql.init.mode: always
  data-source:
    url: "jdbc:sqlite:file::memory:?cache=shared"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      max-lifetime: 0
logging.level.com.sap.cds.messaging: DEBUG
server.port: 4004
cds:
  messaging:
    services:
    - name: "messaging"
      kind: "file-based-messaging"
      binding: "local-messaging.txt"

---
spring.config.activate.on-profile: local-mtxs
logging.level.com.sap.cds.messaging: DEBUG
server.port: 4004
cds:
  data-source:
    auto-config.enabled: true
  multi-tenancy:
    compatibility.enabled: false
    mtxs.enabled: true
    sidecar.url: http://localhost:4005
  messaging:
    services:
    - name: "messaging"
      kind: "file-based-messaging"
      binding: "local-messaging.txt"

---
spring:
    config.activate.on-profile: cloud
    sql.init.mode: never

cds:
    datasource:
        csv.initialization-mode: never

